package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Car {

    @Id
    @JsonIgnore
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
    private long id;

    @ApiModelProperty(value = "Car registration plate", required = true, example = "SR 99500")
    private String registrationPlate;

    @ApiModelProperty(value = "Is the car used for personal reasons?", required = true, example = "true")
    private boolean personalUsage;
}
