package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Car {

    @JsonIgnore
    @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
    private int id;

    @ApiModelProperty(value = "Car registration plate", required = true, example = "SR 99500")
    private String registrationPlate;

    @ApiModelProperty(value = "Is the car used for personal reasons?", required = true, example = "true")
    private boolean personalUsage;
}
