package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class InvoiceEntry {

    @ApiModelProperty(value = "Invoice entry id (generated by application)", required = true, example = "1")
    private int id;

    @ApiModelProperty(value = "Product/service description", required = true, example = "Antenna circuit matching")
    private String description;

    @ApiModelProperty(value = "Number of items", required = true, example = "99")
    private int quantity;

    @ApiModelProperty(value = "Product/service net price", required = true, example = "1500.00")
    private BigDecimal price;

    @ApiModelProperty(value = "Product/service tax value", required = true, example = "510.99")
    @Builder.Default
    private BigDecimal vatValue = BigDecimal.ZERO;

    @ApiModelProperty(value = "Tax rate", required = true)
    private Vat vatRate;

    @ApiModelProperty(value = "Expenses that is related to car")
    private Car carExpenses;

}
